# Generated by Django 5.1.7 on 2025-03-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="time",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="specialty",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="age",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="contact",
        ),
        migrations.AddField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(default="General", max_length=50),
        ),
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(default="unknown@example.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Scheduled", "Scheduled"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
