# Generated by Django 5.1.7 on 2025-04-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_appointment_idx_doctor_date_appointment_idx_status_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="appointment",
            name="idx_doctor_date",
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="idx_status",
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="idx_date",
        ),
    ]
