# Generated by Django 5.1.7 on 2025-04-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_remove_appointment_idx_doctor_date_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["doctor", "date"], name="idx_doctor_date"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="idx_status"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["date"], name="idx_date"),
        ),
    ]
